version: '3'
services:
  backend:
    build: ./app/backend  # Updated path to the backend Dockerfile
    container_name: backend
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=host.docker.internal
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "5000:5000"

  frontend:
    build: ./app/frontend  # Updated path to the Streamlit Dockerfile
    container_name: frontend
    environment:
      - API_URL=http://backend:5000
    ports:
      - "8501:8501"
    depends_on:
      - backend
