version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: leavevisualization123
      POSTGRES_DB: leave_visualization
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://root:leavevisualization123@db/leave_visualization
    ports:
      - "8000:8000"
    command: ["flask", "run", "--host=0.0.0.0", "--port=8000"]
